spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update